language: generic

sudo: required
services:
  - docker

script:
  - docker run --rm -v $TRAVIS_BUILD_DIR:/build -e DNX_BUILD_VERSION=build$TRAVIS_BUILD_NUMBER -w=/build/src/Avast.SmsConnectorClient microsoft/aspnet:1.0.0-rc1-update1 /bin/bash -c "dnu restore && dnu pack"
